// Generates src/db/tables.generated.ts from prisma/schema.prisma: for every model, its PostgreSQL
// schema/table and each column (database name, Prisma type, decimal scale, date-only). Used for
// the table/column identifiers in hand-written SQL (Prisma.sql) and to keep API values unchanged
// (ids as numbers, money as "123.00", dates as "2026-09-29"). Run by `npm run db:generate`.
import { readFileSync, writeFileSync } from 'node:fs';
import path from 'node:path';

const root = path.resolve(import.meta.dirname, '..');
const schema = readFileSync(path.join(root, 'prisma/schema.prisma'), 'utf8');
const SCALARS = new Set(['String', 'Int', 'BigInt', 'Decimal', 'DateTime', 'Boolean', 'Json', 'Float', 'Bytes']);
const lowerFirst = (s) => s[0].toLowerCase() + s.slice(1);

const models = [];
for (const m of schema.matchAll(/^model (\w+) \{\n([\s\S]*?)\n\}/gm)) {
  const [, name, body] = m;
  const table = body.match(/@@map\("([^"]+)"\)/)?.[1] ?? name;
  const dbSchema = body.match(/@@schema\("([^"]+)"\)/)?.[1] ?? 'public';
  const columns = {};
  for (const line of body.split('\n')) {
    const f = line.match(/^\s+(\w+)\s+(\w+)(\[\])?(\?)?(.*)$/);
    if (!f || line.trim().startsWith('@@') || line.trim().startsWith('//')) continue;
    const [, field, type, list, optional, rest] = f;
    if (!SCALARS.has(type)) continue; // relation fields (other models) are not columns
    const column = rest.match(/@map\("([^"]+)"\)/)?.[1] ?? field;
    const dec = rest.match(/@db\.Decimal\((\d+),\s*(\d+)\)/);
    const meta = { column, type, nullable: !!optional };
    if (list) meta.list = true; // PostgreSQL array (e.g. text[])
    if (dec) meta.scale = Number(dec[2]);
    if (/@db\.Date\b/.test(rest)) meta.dateOnly = true;
    columns[field] = meta;
  }
  models.push({ name, delegate: lowerFirst(name), schema: dbSchema, table, columns });
}

const out = [
  '// GENERATED by prisma/gen-tables.mjs from prisma/schema.prisma — do not edit; run `npm run db:generate`.',
  "import { defineTable } from './tableIdentifiers';",
  '',
  ...models.map(
    (m) =>
      `export const ${m.delegate} = defineTable(${JSON.stringify({ model: m.name, delegate: m.delegate, schema: m.schema, table: m.table })}, ${JSON.stringify(m.columns)} as const);`,
  ),
  '',
  '/** Every table, by Prisma model name. */',
  `export const TABLES = { ${models.map((m) => `${m.name}: ${m.delegate}`).join(', ')} } as const;`,
  '',
];

// Prisma result extension: the values the API has always returned (ids as numbers, money as
// "123.00", calendar dates as "YYYY-MM-DD") instead of BigInt / Decimal / Date. Declared per field
// so Prisma Client's TypeScript types say the same.
const conv = ['/**', ' * Prisma result extension (see src/db/client.ts): per model, the fields read back as number / string.', ' */', 'import { fromBigInt, fromDate, fromDecimal } from \'./values\';', '', 'export const resultExtension = {'];
for (const m of models) {
  const fields = Object.entries(m.columns).filter(([, c]) => c.type === 'BigInt' || c.type === 'Decimal' || c.dateOnly);
  if (!fields.length) continue;
  conv.push(`  ${m.delegate}: {`);
  for (const [f, c] of fields) {
    const fn = c.type === 'BigInt' ? `fromBigInt(r.${f})` : c.type === 'Decimal' ? `fromDecimal(r.${f}, ${c.scale ?? 2})` : `fromDate(r.${f})`;
    conv.push(`    ${f}: { needs: { ${f}: true }, compute: (r: { ${f}: ${c.type === 'BigInt' ? 'bigint' : c.type === 'Decimal' ? '{ toFixed(dp: number): string }' : 'Date'}${c.nullable ? ' | null' : ''} }) => ${fn} },`);
  }
  conv.push('  },');
}
conv.push('} as const;', '');
writeFileSync(path.join(root, 'src/db/resultExtension.generated.ts'), ['// GENERATED by prisma/gen-tables.mjs from prisma/schema.prisma — do not edit; run `npm run db:generate`.', ...conv].join('\n'));
writeFileSync(path.join(root, 'src/db/tables.generated.ts'), out.join('\n'));
console.log(`tables.generated.ts: ${models.length} tables`);
